apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: demo-app
metadata:
  annotations:
    description: demo-app template
    openshift.io/display-name: demo-app
    tags: demo-app
    version: 1.0.0
  creationTimestamp: null
  name: demo-app
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        application: ${NAME}-demo-app
      name: ${NAME}-demo-app
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-demo-app
      name: ${NAME}-demo-app
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}-demo-app
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-demo-app
      name: ${NAME}-demo-app
    spec:
      host: ${NAME}-demo-app-demo-project.192.168.99.100.nip.io
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-demo-app
        weight: 100
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        application: ${NAME}-demo-app
      name: ${NAME}-demo-app
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-demo-app:latest
      source:
        contextDir: ${CONTEXT_DIR}
        git:
          ref: ${SOURCE_REPOSITORY_REF}
          uri: ${SOURCE_REPOSITORY_URL}
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ${SOURCE_IMAGE}
            namespace: ${SOURCE_IMAGE_NAMESPACE}
        type: source
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: ${NAME}-demo-app
      name: ${NAME}-demo-app
    spec:
      replicas: 1
      selector:
        deploymentConfig: ${NAME}-demo-app
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            application: ${NAME}-demo-app
            deploymentConfig: ${NAME}-demo-app
          name: ${NAME}-demo-app
        spec:
          containers:
            - image: ${NAME}-demo-app
              imagePullPolicy: Always
              name: ${NAME}-demo-app
              livenessProbe:
                httpGet:
                  scheme: HTTP
                  path: /health
                  port: 8080
                failureThreshold: 60
                initialDelaySeconds: 120
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 15
              readinessProbe:
                httpGet:
                  scheme: HTTP
                  path: /health
                  port: 8080
                failureThreshold: 60
                initialDelaySeconds: 120
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 15
              ports:
                - containerPort: 8080
                  protocol: TCP
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-demo-app
            from:
              kind: ImageStreamTag
              name: ${NAME}-demo-app:latest
          type: ImageChange
        - type: ConfigChange
parameters:
  - displayName: NAME Name
    name: NAME
    required: true
  - description: Git source URI for application
    displayName: Git Repository URL
    name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/amtago/openshift-demo-app.git
  - description: Git branch/tag reference
    displayName: Git Reference
    name: SOURCE_REPOSITORY_REF
    required: true
    value: master
  - displayName: Git context directory
    name: CONTEXT_DIR
    value: /src
  - description: Build source image
    name: SOURCE_IMAGE
    required: true
    value: node:14
  - description: Build source image
    name: SOURCE_IMAGE_NAMESPACE
    required: true
    value: openshift
